"use strict";
exports.__esModule = true;
var express = require("express");
var UserController_1 = require("../controller/UserController");
var Factory_1 = require("../class/Factory");
var validator_1 = require("validator");
var Sanitize_1 = require("../middleware/Sanitize");
var Validation_1 = require("../middleware/Validation");
var router = express.Router();
var controller = new UserController_1["default"](Factory_1.factory.InstanceBcrypt(), Factory_1.factory.InstanceJSONWebToken());
var sanitize = new Sanitize_1["default"](validator_1["default"]);
router.post("/signup", function (req, res, next) { return Validation_1.valid.validationAuth(req, res, next); }, function (req, res, next) { return sanitize.sanitizerAuth(req, res, next); }, function (req, res, next) { return controller.signUp(req, res, next); });
router.post("/login", function (req, res, next) { return Validation_1.valid.validationAuth(req, res, next); }, function (req, res, next) { return sanitize.sanitizerAuth(req, res, next); }, function (req, res, next) { return controller.login(req, res, next); });
exports["default"] = router;
